[project]
name = "backup-cards"
version = "1.0.0"
description = "Backup Cards"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nicegui>=2.1.0",
    "pywebview>=5.0.0",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.16.0",
]
